/* ============================================================
   Assistant - high-level orchestration of JARVIS behavior.
   Maps user/AI intents to a state pipeline + widget reveals +
   simulated audio. Today driven by tap/hold and the debug
   "ASK" buttons; tomorrow by the AI/server.
   ============================================================ */
import { bus } from './EventBus.js';
import { upcomingAppointments, parseLocal } from './Appointments.js';

/** Topic -> widget that should appear when that topic is requested. */
export const TOPIC_WIDGET = {
  orario: 'clock',
  meteo: 'weather',
  sistema: 'stats',
  link: 'links',
  musica: 'wave',
};

/** Map a free-form spoken command to a widget to reveal. */
const COMMAND_PATTERNS = [
  { re: /(meteo|tempo|prevision|temperatur|piov)/i, widget: 'weather' },
  { re: /(ora|orari|che ore|data|giorno|adesso)/i, widget: 'clock' },
  { re: /(sistem|cpu|memori|stato|diagnos|potenz)/i, widget: 'stats' },
  { re: /(musica|canzon|brano|suona|playlist)/i, widget: 'wave' },
  { re: /(link|collegament|applicazion|\bapp\b)/i, widget: 'links' },
];

export function widgetForCommand(text = '') {
  for (const p of COMMAND_PATTERNS) if (p.re.test(text)) return p.widget;
  return null;
}

/** Spoken replies when JARVIS is activated. */
const GREETINGS = [
  'Dimmi',
  'Al tuo servizio Alex',
  'Di cosa hai bisogno?',
  'Presente',
  'Bentornato Signore.',
  'Tutti i sistemi sono online.',
];

/** Spoken lead-ins for the morning briefing. */
const GREETINGS_MORNING = [
  'Buongiorno, Signore.',
  'Buongiorno. Ecco la sua giornata.',
  'Buongiorno. Riepilogo della giornata.',
];

/** Spoken farewells when JARVIS is sent to standby. */
const GOODBYES = [
  'Vado in standby, Signore. Mi richiami quando ha bisogno.',
  'Mi metto in attesa. A presto, Signore.',
  'Sistemi in pausa. Resto in ascolto del suo richiamo, Signore.',
  'Mi disattivo, Signore. Sarò qui non appena pronuncerà il mio nome.',
  'Arrivederci, Signore. È stato un piacere.',
  'Torno in modalità riposo. A sua disposizione quando vorrà.',
];

/** Fixed spoken phrase for actions not yet implemented. */
const DISABLED_PHRASE = 'Funzione non abilitata, mio Signore.';
const ERROR_PHRASE = 'Mi perdoni Signore, ho un problema di connessione.';
const FALLBACK_CONV = 'Temo di non avere una risposta al momento, Signore.';
const MUSIC_NOT_FOUND = 'Non trovo questo brano in libreria, Signore.';

/** Access-code gate phrases. */
const ACCESS_PROMPT = 'Codice di attivazione, Signore.';
const ACCESS_GRANTED = 'Identità confermata. Bentornato, Signore.';
const ACCESS_DENIED = 'Codice errato, Signore. Accesso negato.';

/** How long JARVIS keeps listening for a follow-up after a conversation reply. */
const FOLLOWUP_MS = 5000;

/**
 * Precise spoken commands handled LOCALLY, without calling Gemini (saves
 * tokens + zero latency). Keyed by the exact normalized utterance.
 */
const LOCAL_COMMANDS = {
  // standby
  chiudi: 'standby', standby: 'standby', 'vai in standby': 'standby', spegniti: 'standby',
  // playback
  stop: 'music_stop', ferma: 'music_stop', 'ferma la musica': 'music_stop',
  'ferma musica': 'music_stop', stoppa: 'music_stop', 'stop musica': 'music_stop',
  pausa: 'music_pause', 'metti in pausa': 'music_pause', 'pausa musica': 'music_pause',
  'pausa la musica': 'music_pause', 'in pausa': 'music_pause',
  riprendi: 'music_resume', 'riprendi la musica': 'music_resume', riparti: 'music_resume',
  continua: 'music_resume', 'riprendi musica': 'music_resume',
  avanti: 'music_next', prossima: 'music_next', prossimo: 'music_next',
  'prossima canzone': 'music_next', 'canzone successiva': 'music_next',
  salta: 'music_next', skip: 'music_next', 'traccia successiva': 'music_next',
  indietro: 'music_prev', precedente: 'music_prev', 'canzone precedente': 'music_prev',
  'traccia precedente': 'music_prev', 'torna indietro': 'music_prev',
  // volume
  'alza il volume': 'vol_up', 'piu forte': 'vol_up', 'piu alto': 'vol_up',
  'volume su': 'vol_up', 'aumenta il volume': 'vol_up', 'alza': 'vol_up',
  'abbassa il volume': 'vol_down', 'piu piano': 'vol_down', 'piu basso': 'vol_down',
  'volume giu': 'vol_down', 'abbassa': 'vol_down', 'diminuisci il volume': 'vol_down',
  // morning briefing
  buongiorno: 'briefing', briefing: 'briefing', 'riepilogo': 'briefing',
  'riepilogo della giornata': 'briefing', 'come va la giornata': 'briefing',
};

/**
 * Every phrase JARVIS speaks that is NOT generated by the AI.
 * These get pre-cached so ElevenLabs bills each one only once.
 */
export const FIXED_PHRASES = [
  ...GREETINGS,
  ...GOODBYES,
  DISABLED_PHRASE,
  ERROR_PHRASE,
  FALLBACK_CONV,
  MUSIC_NOT_FOUND,
  ACCESS_PROMPT,
  ACCESS_GRANTED,
  ACCESS_DENIED,
];

export class Assistant {
  constructor({ sm, simulator, widgets, speech = null, voice = null, ai = null, auth = null, music = null, library = null, playlists = null, appointments = null, push = null, apptWidget = null, notes = null, geo = null, weather = null, mail = null }) {
    this.sm = sm;
    this.simulator = simulator;
    this.widgets = widgets;
    this.speech = speech;
    this.voice = voice;
    this.ai = ai;
    this.auth = auth;
    this.music = music;     // MusicPlayer
    this.library = library; // MusicLibrary
    this.playlists = playlists; // Playlists API client
    this.appointments = appointments; // Appointments API client
    this.push = push;       // Web Push registration
    this.apptWidget = apptWidget; // upcoming-reminders HUD widget
    this.notes = notes;     // Notes API client
    this.geo = geo;         // Geo (location + movement speed)
    this.weather = weather; // Weather widget + forecast reporter
    this.mail = mail;       // Mail (IMAP read-only) client
    this.musicHistory = []; // recently played tracks (for "previous")
    this.queue = [];        // active playlist queue (tracks)
    this.queueIdx = -1;     // position within the queue
    // Access session persists across reloads / PWA restarts: once unlocked,
    // JARVIS won't ask for the code again on this device.
    this.authenticated = Assistant._loadAuth();
    this.awaitingCode = false;  // next utterance is treated as the code
    this.timers = new Set();
    this.wakeTimer = null;

    // the waveform follows the audio states automatically
    bus.on('state:change', ({ to }) => {
      if (to === 'listening' || to === 'speaking') this.widgets.show('wave');
      else this.widgets.hide('wave');
    });
  }

  static _loadAuth() {
    try { return localStorage.getItem('jarvis-auth') === '1'; } catch (e) { return false; }
  }

  /** Normalize an utterance for exact local-command matching. */
  static _normCmd(text = '') {
    let t = String(text).toLowerCase().trim();
    // strip accents so "più" == "piu"
    try { t = t.normalize('NFD').replace(/[\u0300-\u036f]/g, ''); } catch (e) { /* noop */ }
    t = t.replace(/[.!?,;:]+$/g, '').replace(/\s+/g, ' ').trim();
    return t;
  }

  /** Map a precise utterance to a local command type, or null. */
  static _localAction(text = '') {
    return LOCAL_COMMANDS[Assistant._normCmd(text)] || null;
  }

  /**
   * Decide whether a terse phrase should run as a hands-free command WITHOUT
   * the wake word. Returns the command text to execute, or null. Music/volume
   * commands only fire when a track is loaded (cuts false positives); standby
   * and the morning briefing fire anytime. Disabled while JARVIS is busy.
   */
  directCommand(text = '') {
    if (!this.sm.is('idle') && !this.sm.is('wake')) return null; // only when not mid-interaction
    const type = Assistant._localAction(text);
    if (!type) return null;
    const isMusicCmd = type.indexOf('music_') === 0 || type === 'vol_up' || type === 'vol_down';
    if (isMusicCmd && !(this.music && this.music.current)) return null;
    return text;
  }

  /**
   * Go to standby: stop any playing music, then speak a farewell and return
   * to idle (wake word required to come back).
   */
  _goStandby() {
    if (this.music && this.music.playing) this.musicStop();
    const bye = GOODBYES[(Math.random() * GOODBYES.length) | 0];
    this._say(bye, { standby: true, cache: true });
  }

  /** Execute a precise local command (no AI round-trip). */
  async _runLocal(type) {
    switch (type) {
      case 'standby': this._goStandby(); return;
      case 'briefing': await this._handleBriefing(); return;
      case 'music_stop': this.musicStop(); this._idleQuiet(); return;
      case 'music_pause': if (this.music) this.music.pause(); this._idleQuiet(); return;
      case 'music_resume':
        if (this.music) { this.music.resume(); this.widgets.show('music'); }
        this._idleQuiet();
        return;
      case 'music_next':
        if (this.musicNext()) this._idleQuiet();
        else this._say(MUSIC_NOT_FOUND, { continueListening: true, cache: true });
        return;
      case 'music_prev':
        if (this.musicPrev()) this._idleQuiet();
        else this._say(MUSIC_NOT_FOUND, { continueListening: true, cache: true });
        return;
      case 'vol_up': if (this.music) this.music.bumpVolume(0.2); this._idleQuiet(); return;
      case 'vol_down': if (this.music) this.music.bumpVolume(-0.2); this._idleQuiet(); return;
      default: this._idleQuiet();
    }
  }

  /**
   * Morning briefing ("Buongiorno"): speak today's weather + the upcoming
   * appointments in a single reply. Both parts are optional/graceful.
   */
  async _handleBriefing() {
    this.sm.force('thinking');
    const clauses = [];

    // Weather (only if we have a position and a reporter)
    if (this.weather && this.geo && this.geo.get && this.geo.get()) {
      try {
        const w = await this.weather.report('today');
        if (w) clauses.push(w.replace(/,?\s*Signore\.?$/i, '')); // drop trailing ", Signore"
      } catch (e) { /* ignore weather failure */ }
    }

    // Appointments
    if (this.appointments) {
      try {
        const c = await this._apptListClause();
        clauses.push(c || 'Non ha impegni in programma');
      } catch (e) { /* ignore agenda failure */ }
    }

    const lead = GREETINGS_MORNING[(Math.random() * GREETINGS_MORNING.length) | 0];
    const body = clauses.length ? ` ${clauses.join('. ')}` : '';
    this._say(`${lead}${body}, Signore.`, { continueListening: false, cache: false });
  }

  _persistAuth(on) {
    this.authenticated = on;
    try {
      if (on) localStorage.setItem('jarvis-auth', '1');
      else localStorage.removeItem('jarvis-auth');
    } catch (e) { /* private mode: keep in-memory only */ }
  }

  _armWake() {
    clearTimeout(this.wakeTimer);
    this.wakeTimer = setTimeout(() => {
      if (this.sm.is('wake')) this.sm.force('idle');
    }, 8000);
  }

  /** Speak a random greeting (sphere reacts to the real voice), then run onDone. */
  greet(onDone) {
    this._clear();
    if (this.voice) this.voice.hold(); // don't transcribe our own voice
    this.sm.force('speaking');
    const phrase = GREETINGS[(Math.random() * GREETINGS.length) | 0];
    if (this.speech) {
      // NeuralTTS drives the audio level itself (real amplitude). Fixed -> cache.
      this.speech.speak(phrase, () => { if (onDone) onDone(); }, { cache: true });
    } else {
      this._later(() => { if (onDone) onDone(); }, 700);
    }
  }

  _later(fn, ms) {
    const id = setTimeout(() => { this.timers.delete(id); fn(); }, ms);
    this.timers.add(id);
    return id;
  }

  _clear() {
    for (const id of this.timers) clearTimeout(id);
    this.timers.clear();
    clearTimeout(this.wakeTimer);
  }

  /** Tap on the sphere: activate (with greeting), or deactivate. */
  wake() {
    if (this.sm.is('idle')) {
      // First activation while locked: no greeting, ask for the code.
      if (this.auth && !this.authenticated) {
        this._requestCode();
        return;
      }
      this.greet(() => {
        this.sm.force('wake');
        this._armWake();
        if (this.voice) this.voice.resumeWake();
      });
    } else {
      this.deactivate();
    }
  }

  /** Press-and-hold begins: listening. */
  startListening() {
    this._clear();
    this.sm.force('listening');
    this.simulator.start('listening');
  }

  /** Release after hold: process then respond (no specific widget). */
  endListening() {
    this._clear();
    this.simulator.stop();
    this._respond(null);
  }

  /** A concrete request (e.g. from voice/AI): respond + reveal widget. */
  request(topic) {
    this._clear();
    this.simulator.stop();
    this._respond(TOPIC_WIDGET[topic] || null);
  }

  /**
   * Ask for the activation code instead of greeting (used while locked).
   * Goes straight to listening for the spoken code.
   */
  _requestCode() {
    this._clear();
    if (this.voice) this.voice.hold();
    this.awaitingCode = true;
    bus.emit('ai:result', { text: '', intent: 'access_required', reply: '' });
    this._say(ACCESS_PROMPT, { continueListening: true, grace: 8000, cache: true });
  }

  /** Wake word recognized: greet, then start listening for the command. */
  voiceWake() {
    // First activation while locked: no greeting, ask for the code.
    if (this.auth && !this.authenticated) {
      this._requestCode();
      return;
    }
    // While music plays, skip the greeting and go straight to listening so
    // "stop" / "skip" feel instant (music ducks during the listening state).
    if (this.music && this.music.playing) {
      this._clear();
      if (this.voice) this.voice.hold();
      this.sm.force('listening');
      this.simulator.start('listening');
      if (this.voice) this.voice.resumeCommand();
      return;
    }
    this.greet(() => {
      this.sm.force('listening');
      this.simulator.start('listening');
      if (this.voice) this.voice.resumeCommand();
    });
  }

  /**
   * Spoken command captured: ask the AI, classify the intent, then
   * speak. Only "conversation" gets a real reply; the other actions
   * are not implemented yet and get a fixed phrase.
   */
  async voiceEnd(text) {
    this._clear();
    this.simulator.stop();
    if (this.voice) this.voice.hold();

    // ---- access gate: must unlock with the code before talking ----
    if (this.auth && !this.authenticated) {
      this.sm.force('thinking');
      if (this.awaitingCode) {
        const ok = await this.auth.verify(text);
        bus.emit('ai:result', { text, intent: ok ? 'access_granted' : 'access_denied', reply: '' });
        if (ok) {
          this._persistAuth(true);
          this.awaitingCode = false;
          this._say(ACCESS_GRANTED, { continueListening: true, cache: true });
        } else {
          this._say(ACCESS_DENIED, { continueListening: true, grace: 8000, cache: true });
        }
        return;
      }
      // first command while locked: ask for the activation code
      this.awaitingCode = true;
      bus.emit('ai:result', { text, intent: 'access_required', reply: '' });
      this._say(ACCESS_PROMPT, { continueListening: true, grace: 8000, cache: true });
      return;
    }

    // ---- precise local commands: skip the AI entirely (saves tokens) ----
    const local = Assistant._localAction(text);
    if (local) {
      const intent = local === 'standby' ? 'standby' : (local === 'briefing' ? 'briefing' : 'music');
      bus.emit('ai:result', { text, intent, reply: '' });
      await this._runLocal(local);
      return;
    }

    this.sm.force('thinking');

    let result = { intent: 'conversation', reply: '' };
    if (this.ai) {
      const nowPlaying = this.music && this.music.current ? this.music.current : null;
      const speed = this.geo && typeof this.geo.speedKmh === 'function' ? this.geo.speedKmh() : null;
      result = await this.ai.ask(text, { nowPlaying, speed });
    }
    bus.emit('ai:result', {
      text,
      intent: result.intent,
      reply: result.reply,
      remembered: result.remembered || [],
      error: result.error,
    });

    // Standby: say a farewell (fixed -> cached), then go fully to standby.
    if (result.intent === 'standby') {
      this._goStandby();
      return;
    }

    // Music: JARVIS stays silent and just drives the player + widget.
    if (result.intent === 'music') {
      this._handleMusic(result, text);
      return;
    }

    // Appointment: save it server-side; the cron + Web Push deliver reminders.
    if (result.intent === 'appointment') {
      await this._handleAppointment(result);
      return;
    }

    // Note: write / append / read / list / delete / download a text note.
    if (result.intent === 'note') {
      await this._handleNote(result);
      return;
    }

    // Navigation: launch Google Maps turn-by-turn toward the destination.
    if (result.intent === 'navigation') {
      this._handleNavigation(result);
      return;
    }

    // Weather: speak the real forecast (Open-Meteo via the device GPS).
    if (result.intent === 'weather') {
      await this._handleWeather(result);
      return;
    }

    // Timer / alarm: scheduled via the appointments backend (cron + push) and
    // also fired locally while the app stays open.
    if (result.intent === 'timer') {
      await this._handleTimer(result);
      return;
    }

    // Mail: read-only IMAP — unread count, read or summarize the latest.
    if (result.intent === 'mail') {
      await this._handleMail(result);
      return;
    }

    // Update the access code (only reachable once authenticated).
    if (result.intent === 'update_access_code') {
      const newCode = (result.accessCode || '').trim();
      if (!newCode) {
        this._say('Non ho colto il nuovo codice, Signore.', { continueListening: true, cache: false });
        return;
      }
      const ok = this.auth ? await this.auth.update(newCode) : false;
      if (ok) {
        this._say(`Codice di accesso aggiornato. Il nuovo codice è: ${newCode}, Signore.`,
          { continueListening: true, cache: false });
      } else {
        this._say('Non sono riuscito ad aggiornare il codice, Signore.', { continueListening: true, cache: false });
      }
      return;
    }

    let replyText;
    let keepListening = false;
    let cache = true; // fixed phrases are cached; dynamic replies are not
    if (result.intent === 'conversation') {
      if (result.reply) {
        replyText = result.reply;
        keepListening = true;       // stay open for the user's follow-up
        cache = false;              // dynamic -> never cache
      } else if (result.error) {
        replyText = ERROR_PHRASE;   // fixed
        keepListening = true;       // transient (e.g. rate limit) -> let them retry
      } else {
        replyText = FALLBACK_CONV;  // fixed
      }
    } else {
      replyText = DISABLED_PHRASE; // safety net for any unhandled action intent
    }
    this._say(replyText, { continueListening: keepListening, cache });
  }

  /**
   * Music intent: play / shuffle / next / prev / pause / resume / stop,
   * all without speaking. The "now playing" widget shows title + artist
   * with a bass-reactive equalizer.
   */
  _handleMusic(result, utterance = '') {
    const action = result.musicAction || (result.musicStop ? 'stop' : 'play');

    // ---- playlist management (these may speak a short confirmation) ----
    if (action && action.indexOf('playlist_') === 0) {
      this._handlePlaylist(action, result, utterance);
      return;
    }

    if (action === 'stop') { this.musicStop(); this._idleQuiet(); return; }
    if (action === 'pause') { if (this.music) this.music.pause(); this._idleQuiet(); return; }
    if (action === 'resume') {
      if (this.music) { this.music.resume(); this.widgets.show('music'); }
      this._idleQuiet();
      return;
    }
    if (action === 'shuffle') {
      this._clearQueue(); // break out of any playlist into free shuffle
      if (this.musicNext()) this._idleQuiet();
      else this._say(MUSIC_NOT_FOUND, { continueListening: true, cache: true });
      return;
    }
    if (action === 'next') {
      if (this.musicNext()) this._idleQuiet();
      else this._say(MUSIC_NOT_FOUND, { continueListening: true, cache: true });
      return;
    }
    if (action === 'prev') {
      if (this.musicPrev()) this._idleQuiet();
      else this._say(MUSIC_NOT_FOUND, { continueListening: true, cache: true });
      return;
    }

    // "un'altra di questo artista": same artist, different track
    if (result.musicArtist && !result.musicTitle && this.library && this.music && this.music.current) {
      const cur = this.music.current.file;
      const sameArtist = this.library.byArtist(result.musicArtist, cur);
      if (sameArtist) { this.playTrack(sameArtist); this._idleQuiet(); return; }
    }

    // play: a specific request, or generic -> random fallback
    const track = this.library
      ? this.library.resolve(result.musicArtist, result.musicTitle, utterance)
      : null;
    if (track) { this.playTrack(track); this._idleQuiet(); return; }
    if (this.musicNext()) this._idleQuiet();
    else this._say(MUSIC_NOT_FOUND, { continueListening: true, cache: true });
  }

  /**
   * Playlist actions: play / create / add / remove / delete / list.
   * Playing is silent (like music); management speaks a short confirmation.
   */
  async _handlePlaylist(action, result, utterance = '') {
    if (!this.playlists || !this.library) {
      this._say('Le playlist non sono disponibili, Signore.', { continueListening: true, cache: false });
      return;
    }
    const name = (result.playlistName || '').trim();
    const picks = Array.isArray(result.playlistTracks) ? result.playlistTracks : [];

    if (action === 'playlist_list') {
      const all = await this.playlists.list();
      if (!all.length) { this._say('Non ha ancora nessuna playlist, Signore.', { continueListening: false, cache: false }); return; }
      const names = all.map((p) => p.name).join(', ');
      this._say(`Le sue playlist, Signore: ${names}.`, { continueListening: false, cache: false });
      return;
    }

    if (!name) {
      this._say('Non ho colto il nome della playlist, Signore.', { continueListening: true, cache: false });
      return;
    }

    if (action === 'playlist_play') {
      const pl = await this.playlists.get(name);
      if (!pl || !Array.isArray(pl.tracks) || !pl.tracks.length) {
        this._say(`Non trovo la playlist ${name}, Signore.`, { continueListening: true, cache: false });
        return;
      }
      this._playQueue(pl.tracks);
      this._idleQuiet();
      return;
    }

    if (action === 'playlist_delete') {
      const r = await this.playlists.delete(name);
      if (r && r.ok) this._say(`Playlist ${name} eliminata, Signore.`, { continueListening: false, cache: false });
      else this._say(`Non trovo la playlist ${name}, Signore.`, { continueListening: true, cache: false });
      return;
    }

    // create / add / remove all work on a resolved track list
    const tracks = this.library.resolveMany(picks.length ? picks : [utterance]);

    if (action === 'playlist_remove') {
      const titles = picks.map((p) => (typeof p === 'string' ? p : (p && p.title) || '')).filter(Boolean);
      const r = await this.playlists.remove(name, {
        files: tracks.map((t) => t.file),
        titles,
      });
      const n = r && r.playlist ? (r.playlist.tracks || []).length : 0;
      if (r && r.ok) this._say(`Aggiornata la playlist ${name}: ${n} brani, Signore.`, { continueListening: false, cache: false });
      else this._say(`Non trovo la playlist ${name}, Signore.`, { continueListening: true, cache: false });
      return;
    }

    if (!tracks.length) {
      this._say('Non ho riconosciuto i brani da inserire, Signore.', { continueListening: true, cache: false });
      return;
    }

    const r = action === 'playlist_add'
      ? await this.playlists.add(name, tracks)
      : await this.playlists.create(name, tracks);
    if (r && r.ok) {
      const n = r.playlist ? (r.playlist.tracks || []).length : tracks.length;
      const verb = action === 'playlist_add' ? 'Aggiornata' : 'Creata';
      this._say(`${verb} la playlist ${name} con ${n} brani, Signore.`, { continueListening: false, cache: false });
    } else {
      this._say(`Non sono riuscito a salvare la playlist ${name}, Signore.`, { continueListening: true, cache: false });
    }
  }

  /** Play a specific track, remembering the previous one for "prev". */
  playTrack(track, { keepQueue = false } = {}) {
    if (!track || !this.music) return;
    if (!keepQueue) this._clearQueue();
    if (this.music.current) {
      this.musicHistory.push(this.music.current);
      if (this.musicHistory.length > 50) this.musicHistory.shift();
    }
    this.music.play(track);
    this.widgets.show('music');
  }

  /** Start playing a queue of tracks (a playlist). */
  _playQueue(tracks) {
    this.queue = (tracks || []).filter((t) => t && t.file);
    this.queueIdx = 0;
    if (this.queue.length) this.playTrack(this.queue[0], { keepQueue: true });
  }

  _clearQueue() {
    this.queue = [];
    this.queueIdx = -1;
  }

  /**
   * Advance playback: within an active playlist queue step to the next
   * track; otherwise play a random one (shuffle / skip).
   * @returns {boolean} played
   */
  musicNext() {
    if (!this.music) return false;
    // queued playlist: advance to the next track in order
    if (this.queue.length && this.queueIdx >= 0) {
      if (this.queueIdx < this.queue.length - 1) {
        this.queueIdx++;
        this.playTrack(this.queue[this.queueIdx], { keepQueue: true });
        return true;
      }
      this._clearQueue(); // playlist finished -> stop here
      return false;
    }
    if (!this.library) return false;
    const cur = this.music.current && this.music.current.file;
    const t = this.library.random(cur);
    if (!t) return false;
    this.playTrack(t);
    return true;
  }

  /** Go back to the previously played track. @returns {boolean} played */
  musicPrev() {
    const prev = this.musicHistory.pop();
    if (prev && this.music) {
      this.music.play(prev); // not via playTrack: don't re-stack history
      this.widgets.show('music');
      return true;
    }
    return this.musicNext();
  }

  /** Stop playback and hide the widget. */
  musicStop() {
    this._clearQueue();
    if (this.music) this.music.stop();
    this.widgets.hide('music');
  }

  /**
   * Appointment intent: add / list / delete. Add persists server-side (cron +
   * Web Push deliver reminders); list speaks the upcoming ones; delete removes
   * a matching one. The HUD widget mirrors the upcoming reminders.
   */
  async _handleAppointment(result) {
    const ops = Array.isArray(result.appointmentOps) ? result.appointmentOps : [];
    if (!this.appointments) {
      this._say('L\u2019agenda non \u00e8 disponibile, Signore.', { continueListening: true, cache: false });
      return;
    }
    if (!ops.length) {
      this._say('Non ho colto i dettagli dell\u2019impegno, Signore.', { continueListening: true, cache: false });
      return;
    }

    // Pure "che impegni ho?" request.
    if (ops.length === 1 && ops[0].action === 'list') { await this._handleApptList(); return; }

    // Execute every operation in order, collecting spoken clauses.
    const clauses = [];
    let wantsList = false;
    for (const op of ops) {
      if (op.action === 'list') { wantsList = true; continue; }
      const clause = op.action === 'delete'
        ? await this._apptDeleteOp(op)
        : await this._apptAddOp(op);
      if (clause) clauses.push(clause);
    }

    if (this.push) this.push.enable(); // ensure this device can receive reminders
    this._refreshApptWidget();

    if (wantsList) {
      const listClause = await this._apptListClause();
      if (listClause) clauses.push(listClause);
    }
    if (!clauses.length) {
      this._say('Non sono riuscito a completare la richiesta, Signore.', { continueListening: true, cache: false });
      return;
    }
    this._say(`${clauses.join('. ')}, Signore.`, { continueListening: false, cache: false });
  }

  /** Add one appointment; returns a spoken clause (or '' on failure). */
  async _apptAddOp(op) {
    const title = (op.title || '').trim();
    const datetime = (op.datetime || '').trim();
    if (!title || !datetime) return '';
    const r = await this.appointments.add({
      title,
      datetime,
      all_day: !!op.allDay,
      recurrence: op.recurrence || 'none',
      reminders: Array.isArray(op.reminders) ? op.reminders : [],
      notes: op.notes || '',
    });
    if (!(r && r.ok)) return '';
    const appt = r.appointment || { title, datetime, all_day: op.allDay, recurrence: op.recurrence };
    const when = this._whenText(appt.datetime, appt.all_day);
    const rec = { daily: ' ogni giorno', weekly: ' ogni settimana', monthly: ' ogni mese', yearly: ' ogni anno' }[appt.recurrence] || '';
    return `Fissato ${appt.title} per ${when}${rec}`;
  }

  /** Delete appointments (all / by date / by title); returns a spoken clause. */
  async _apptDeleteOp(op) {
    const scope = op.deleteScope || (op.deleteDate ? 'date' : (op.title ? 'title' : ''));
    if (scope === 'all') {
      const r = await this.appointments.deleteAll();
      return (r && r.deleted) ? 'Cancellati tutti gli impegni' : 'Non c\u2019erano impegni da cancellare';
    }
    if (scope === 'date' && op.deleteDate) {
      const r = await this.appointments.deleteByDate(op.deleteDate);
      const label = this._dayLabel(op.deleteDate);
      return (r && r.deleted) ? `Cancellati gli impegni di ${label}` : `Non ha impegni ${label}`;
    }
    const title = (op.title || '').trim();
    if (!title) return '';
    const r = await this.appointments.deleteByTitle(title);
    if (r && r.deleted) {
      const t = (r.titles && r.titles[0]) || title;
      return r.deleted > 1 ? `Cancellati ${r.deleted} impegni` : `Cancellato ${t}`;
    }
    return `Non trovo ${title} in agenda`;
  }

  /** Speak (and show) the next few upcoming reminders. */
  async _handleApptList() {
    const clause = await this._apptListClause();
    if (!clause) {
      this._say('Non ha impegni in programma, Signore.', { continueListening: false, cache: false });
      return;
    }
    this._say(`${clause}, Signore.`, { continueListening: false, cache: false });
  }

  /** Build the spoken upcoming-reminders clause and reveal the widget. */
  async _apptListClause() {
    const appts = await this.appointments.list();
    const up = upcomingAppointments(appts, 3);
    this._refreshApptWidget();
    if (!up.length) return '';
    if (this.apptWidget) this.widgets.show('appointments', 18000);
    const parts = up.map(({ appt, occ }) => `${appt.title}, ${this._whenTextDate(occ, appt.all_day)}`);
    const lead = up.length === 1 ? 'Ha un impegno in programma' : `Ha ${up.length} impegni in programma`;
    return `${lead}: ${parts.join('; ')}`;
  }

  _refreshApptWidget() {
    if (this.apptWidget && this.apptWidget.refresh) this.apptWidget.refresh();
  }

  /**
   * Note intent: add / append / read / list / delete / download. Content is
   * already structured by the AI; here we just persist it, speak a short
   * confirmation, and (for "download") save a .txt onto the device.
   */
  async _handleNote(result) {
    if (!this.notes) {
      this._say('Le note non sono disponibili, Signore.', { continueListening: true, cache: false });
      return;
    }
    const action = result.noteAction || 'add';
    const title = (result.noteTitle || '').trim();
    const content = (result.noteContent || '').trim();

    if (action === 'list') {
      const all = await this.notes.list();
      if (!all.length) { this._say('Non ha ancora nessuna nota, Signore.', { continueListening: false, cache: false }); return; }
      const names = all.map((n) => n.title).filter(Boolean).join(', ');
      this._say(`Le sue note, Signore: ${names}.`, { continueListening: false, cache: false });
      return;
    }

    if (action === 'read') {
      const n = title ? await this.notes.get({ title }) : null;
      if (!n) { this._say(`Non trovo la nota ${title || 'richiesta'}, Signore.`, { continueListening: true, cache: false }); return; }
      this._speakNote(n);
      return;
    }

    if (action === 'search') {
      if (!title) { this._say('Cosa cerco tra le note, Signore?', { continueListening: true, cache: false }); return; }
      const r = await this.notes.search(title);
      if (!r || !r.note) {
        this._say(`Non ho trovato note su ${title}, Signore.`, { continueListening: true, cache: false });
        return;
      }
      this._speakNote(r.note, `Ho trovato la nota ${r.note.title}. `);
      return;
    }

    if (action === 'delete') {
      if (!title) { this._say('Quale nota devo eliminare, Signore?', { continueListening: true, cache: false }); return; }
      const r = await this.notes.delete({ title });
      if (r && r.ok) this._say(`Nota ${title} eliminata, Signore.`, { continueListening: false, cache: false });
      else this._say(`Non trovo la nota ${title}, Signore.`, { continueListening: true, cache: false });
      return;
    }

    if (action === 'download') {
      if (!title) { this._say('Quale nota devo scaricare, Signore?', { continueListening: true, cache: false }); return; }
      const r = await this.notes.download({ title });
      if (r && r.ok) this._say(`Sto scaricando la nota ${title}, Signore.`, { continueListening: false, cache: false });
      else this._say(`Non sono riuscito a scaricare la nota ${title}, Signore.`, { continueListening: true, cache: false });
      return;
    }

    // add / append
    if (!content) {
      this._say('Non ho colto il contenuto della nota, Signore.', { continueListening: true, cache: false });
      return;
    }
    const r = action === 'append'
      ? await this.notes.append(title, content)
      : await this.notes.add(title, content);
    if (r && r.ok) {
      const t = (r.note && r.note.title) || title || 'nota';
      const verb = action === 'append' ? 'Aggiornata' : 'Salvata';
      this._say(`${verb} la nota ${t}, Signore.`, { continueListening: false, cache: false });
    } else {
      this._say('Non sono riuscito a salvare la nota, Signore.', { continueListening: true, cache: false });
    }
  }

  /** Speak a note's content (bullets flattened to pauses). */
  _speakNote(n, lead = '') {
    const spoken = (n.content || '')
      .replace(/^\s*[-*]\s?/gm, '')
      .replace(/\s*\n+\s*/g, '. ')
      .trim();
    const head = lead || `Nota ${n.title}. `;
    this._say(`${head}${spoken || 'È vuota'}, Signore.`, { continueListening: false, cache: false });
  }

  /** Italian spoken date from a "YYYY-MM-DD HH:MM" string. */
  _whenText(datetime, allDay) {
    const d = new Date(String(datetime).replace(' ', 'T'));
    if (isNaN(d)) return datetime;
    return this._whenTextDate(d, allDay);
  }

  /** Italian spoken date from a Date; omits the time for all-day events. */
  _whenTextDate(date, allDay) {
    try {
      const opts = allDay
        ? { weekday: 'long', day: 'numeric', month: 'long' }
        : { weekday: 'long', day: 'numeric', month: 'long', hour: '2-digit', minute: '2-digit' };
      let s = new Intl.DateTimeFormat('it-IT', opts).format(date);
      if (!allDay) s = s.replace(',', ' alle');
      return s;
    } catch (e) { return ''; }
  }

  /** "oggi" / "domani" / "il 10 giugno" for a "YYYY-MM-DD" date. */
  _dayLabel(dateYmd) {
    const m = String(dateYmd).match(/^(\d{4})-(\d{2})-(\d{2})/);
    if (!m) return 'quel giorno';
    const d = new Date(+m[1], +m[2] - 1, +m[3]);
    const now = new Date();
    if (d.toDateString() === now.toDateString()) return 'oggi';
    const tom = new Date(now); tom.setDate(now.getDate() + 1);
    if (d.toDateString() === tom.toDateString()) return 'domani';
    try {
      return 'il ' + new Intl.DateTimeFormat('it-IT', { day: 'numeric', month: 'long' }).format(d);
    } catch (e) { return 'quel giorno'; }
  }

  /**
   * Navigation intent: speak a short confirmation, then hand off to Google
   * Maps. On Android the "google.navigation:" scheme starts turn-by-turn
   * directly (zero extra taps once Maps is the default handler); elsewhere
   * the universal Maps URL opens with navigation requested. The destination
   * (home/work) is already resolved to a real address server-side.
   */
  _handleNavigation(result) {
    const dest = (result.navDestination || '').trim();
    const mode = result.navMode || 'driving';
    const label = (result.navLabel || '').trim() || dest;
    if (!dest) {
      this._say(`Non ho l'indirizzo per ${label || 'quella destinazione'}, Signore.`,
        { continueListening: true, cache: false });
      return;
    }
    const url = this._mapsUrl(dest, mode);

    // Speak first, then navigate away (leaving the PWA for Maps).
    if (this.voice) this.voice.hold();
    this.sm.force('speaking');
    const go = () => { try { window.location.href = url; } catch (e) { /* ignore */ } };
    if (this.speech) this.speech.speak(`Avvio la navigazione verso ${label}, Signore.`, go, { cache: false });
    else { this._later(go, 600); }
  }

  /** Weather intent: speak the real forecast and reveal the weather widget. */
  async _handleWeather(result) {
    if (!this.weather) {
      this._say('Il meteo non è disponibile, Signore.', { continueListening: true, cache: false });
      return;
    }
    const pos = this.geo && this.geo.get && this.geo.get();
    if (!pos) {
      this._say('Non ho ancora la sua posizione, Signore. Conceda l\u2019accesso alla localizzazione.',
        { continueListening: true, cache: false });
      return;
    }
    let spoken = null;
    try { spoken = await this.weather.report(result.weatherWhen || 'today'); }
    catch (e) { spoken = null; }
    if (!spoken) {
      this._say('Non riesco a recuperare il meteo al momento, Signore.', { continueListening: true, cache: false });
      return;
    }
    this.widgets.show('weather', 16000);
    this._say(spoken, { continueListening: false, cache: false });
  }

  /**
   * Timer / alarm intent. A timer is stored as an appointment that fires a
   * reminder AT its time (offset "0m"), so the existing cron + Web Push deliver
   * it even with the app closed. While the app is open we also fire it locally
   * (a chime + spoken alert).
   */
  async _handleTimer(result) {
    if (!this.appointments) {
      this._say('I timer non sono disponibili, Signore.', { continueListening: true, cache: false });
      return;
    }
    const action = result.timerAction || 'set';
    const label = (result.timerLabel || '').trim();

    if (action === 'list') { await this._handleApptList(); return; }

    if (action === 'cancel') {
      const r = label ? await this.appointments.deleteByTitle(label) : null;
      this._clearLocalTimers(label);
      if (r && r.deleted) this._say(`Timer ${label} annullato, Signore.`, { continueListening: false, cache: false });
      else this._say('Ho annullato i timer locali, Signore.', { continueListening: false, cache: false });
      this._refreshApptWidget();
      return;
    }

    // ---- set ----
    const recurrence = result.timerRecurrence === 'daily' ? 'daily' : 'none';
    let when = parseLocal(result.timerDatetime);
    if (!when) {
      this._say('Non ho colto l\u2019orario del timer, Signore.', { continueListening: true, cache: false });
      return;
    }
    // One-off clock time already past today -> roll to the next day.
    if (recurrence === 'none' && when.getTime() <= Date.now()) {
      when = new Date(when.getTime() + 86400000);
    }
    const isAlarm = recurrence === 'daily' || this._looksLikeAlarm(when);
    const title = label || (isAlarm ? 'Sveglia' : 'Timer');
    const datetime = this._fmtLocal(when);

    const r = await this.appointments.add({
      title,
      datetime,
      recurrence,
      reminders: ['0m'],   // fire exactly at the time
      notes: 'timer',
    });
    if (!(r && r.ok)) {
      this._say('Non sono riuscito a impostare il timer, Signore.', { continueListening: true, cache: false });
      return;
    }
    if (this.push) this.push.enable();
    this._refreshApptWidget();
    this._scheduleLocalTimer(when, title);

    const spoken = this._timerConfirm(when, title, recurrence);
    this._say(spoken, { continueListening: false, cache: false });
  }

  /** Heuristic: a time at least ~6h away phrased as a clock time reads as an alarm. */
  _looksLikeAlarm(date) {
    return (date.getTime() - Date.now()) > 6 * 3600 * 1000;
  }

  /** Spoken confirmation, relative for short timers, absolute for alarms. */
  _timerConfirm(date, title, recurrence) {
    const ms = date.getTime() - Date.now();
    const mins = Math.round(ms / 60000);
    if (recurrence === 'daily') {
      const hhmm = new Intl.DateTimeFormat('it-IT', { hour: '2-digit', minute: '2-digit' }).format(date);
      return `Sveglia impostata ogni giorno alle ${hhmm}, Signore.`;
    }
    if (mins <= 90 && mins >= 1) {
      const lbl = title && title !== 'Timer' ? ` per ${title}` : '';
      return mins === 1 ? `Timer${lbl} impostato, suono tra un minuto, Signore.`
        : `Timer${lbl} impostato, suono tra ${mins} minuti, Signore.`;
    }
    const when = this._whenTextDate(date, false);
    return `Promemoria impostato per ${when}, Signore.`;
  }

  /** Format a Date as the backend's "YYYY-MM-DD HH:MM" local string. */
  _fmtLocal(d) {
    const p = (n) => String(n).padStart(2, '0');
    return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}`;
  }

  /** Schedule an in-app alarm (chime + voice) if the target is within ~26h. */
  _scheduleLocalTimer(date, label) {
    const ms = date.getTime() - Date.now();
    if (ms <= 0 || ms > 26 * 3600 * 1000) return; // out of local range -> push handles it
    if (!this._localTimers) this._localTimers = [];
    const id = setTimeout(() => this._fireLocalTimer(label), ms);
    this._localTimers.push({ id, label });
  }

  _clearLocalTimers(label = '') {
    if (!this._localTimers) return;
    const keep = [];
    for (const t of this._localTimers) {
      if (!label || (t.label || '').toLowerCase() === label.toLowerCase()) clearTimeout(t.id);
      else keep.push(t);
    }
    this._localTimers = keep;
  }

  /** An alarm fired while the app is open: chime, then announce it. */
  _fireLocalTimer(label) {
    if (this._localTimers) this._localTimers = this._localTimers.filter((t) => t.label !== label);
    this._chime();
    this.widgets.show('appointments', 18000);
    this._refreshApptWidget();
    const what = label && label !== 'Timer' && label !== 'Sveglia' ? ` ${label}` : '';
    this._later(() => {
      this._say(`È ora, Signore.${what}`, { continueListening: false, cache: false });
    }, 700);
  }

  /** Short rising chime via Web Audio (no asset needed). */
  _chime() {
    try {
      const AC = window.AudioContext || window.webkitAudioContext;
      if (!AC) return;
      const ctx = new AC();
      const now = ctx.currentTime;
      [880, 1175, 1568].forEach((f, i) => {
        const o = ctx.createOscillator();
        const g = ctx.createGain();
        o.type = 'sine';
        o.frequency.value = f;
        const t = now + i * 0.18;
        g.gain.setValueAtTime(0.0001, t);
        g.gain.exponentialRampToValueAtTime(0.3, t + 0.03);
        g.gain.exponentialRampToValueAtTime(0.0001, t + 0.32);
        o.connect(g); g.connect(ctx.destination);
        o.start(t); o.stop(t + 0.34);
      });
      setTimeout(() => { try { ctx.close(); } catch (e) { /* noop */ } }, 1500);
    } catch (e) { /* audio unavailable: the spoken alert still fires */ }
  }

  /**
   * Mail intent (read-only IMAP). unread -> count + senders; read -> speak the
   * latest message; summary -> speak a Gemini summary; list -> recent senders.
   * Common failures (extension/credentials) get a clear spoken message.
   */
  async _handleMail(result) {
    if (!this.mail) {
      this._say('La posta non è configurata, Signore.', { continueListening: true, cache: false });
      return;
    }
    const action = result.mailAction || 'unread';
    this.sm.force('thinking');

    if (action === 'unread') {
      const r = await this.mail.unread();
      if (!r || !r.ok) { this._sayMailError(r); return; }
      if (!r.count) { this._say('Nessuna email non letta, Signore.', { continueListening: false, cache: false }); return; }
      const items = Array.isArray(r.items) ? r.items.slice(0, 3) : [];
      const who = items.map((m) => m.fromName).filter(Boolean);
      const tail = who.length ? ` Le più recenti da ${who.join(', ')}.` : '';
      const n = r.count === 1 ? 'una email non letta' : `${r.count} email non lette`;
      this._say(`Ha ${n}, Signore.${tail}`, { continueListening: false, cache: false });
      return;
    }

    if (action === 'list') {
      const r = await this.mail.list();
      if (!r || !r.ok) { this._sayMailError(r); return; }
      const items = Array.isArray(r.items) ? r.items.slice(0, 4) : [];
      if (!items.length) { this._say('La casella è vuota, Signore.', { continueListening: false, cache: false }); return; }
      const parts = items.map((m) => `${m.fromName}, ${m.subject}`);
      this._say(`Email recenti, Signore: ${parts.join('; ')}.`, { continueListening: false, cache: false });
      return;
    }

    if (action === 'summary') {
      const r = await this.mail.summary({ unseen: true });
      if (!r || !r.ok || !r.mail) { this._sayMailError(r); return; }
      const m = r.mail;
      const body = (m.summary && m.summary.trim()) ? m.summary : (m.body || '').trim();
      if (!body) { this._say(`Email da ${m.fromName}, oggetto ${m.subject}. Non sono riuscito a riassumerla, Signore.`, { continueListening: false, cache: false }); return; }
      this._say(`Email da ${m.fromName}. ${body}`, { continueListening: false, cache: false });
      return;
    }

    // read (default for content)
    const r = await this.mail.read({ unseen: true });
    if (!r || !r.ok || !r.mail) { this._sayMailError(r); return; }
    const m = r.mail;
    const body = (m.body || '').replace(/\s*\n+\s*/g, '. ').trim();
    const intro = `Email da ${m.fromName}${m.when ? `, ${m.when}` : ''}. Oggetto: ${m.subject}.`;
    this._say(`${intro} ${body || 'Il corpo è vuoto'}, Signore.`, { continueListening: false, cache: false });
  }

  /** Speak a friendly message for a mail backend failure. */
  _sayMailError(r) {
    const err = (r && r.error) || '';
    let msg = 'Non riesco ad accedere alla posta, Signore.';
    if (/extension/i.test(err)) msg = 'Il modulo di posta non è abilitato sul server, Signore.';
    else if (/not configured|disabled/i.test(err)) msg = 'La posta non è ancora configurata, Signore.';
    this._say(msg, { continueListening: true, cache: false });
  }

  /** Build the best Maps navigation URL for the platform. */
  _mapsUrl(dest, mode = 'driving') {
    const q = encodeURIComponent(dest);
    const isAndroid = /Android/i.test((navigator && navigator.userAgent) || '');
    if (isAndroid) {
      const m = { driving: 'd', walking: 'w', transit: 'r', bicycling: 'b' }[mode] || 'd';
      return `google.navigation:q=${q}&mode=${m}`;
    }
    return `https://www.google.com/maps/dir/?api=1&destination=${q}`
      + `&travelmode=${encodeURIComponent(mode)}&dir_action=navigate`;
  }

  /** Return to idle without speaking (used after starting/stopping music). */
  _idleQuiet() {
    this.simulator.stop();
    this.sm.force('idle');
    if (this.voice) this.voice.resumeWake();
  }

  /**
   * Speak a phrase, then:
   *  - continueListening: stay in listening mode for FOLLOWUP_MS (no wake word);
   *  - standby: hide widgets and return to idle (wake word required again);
   *  - default: return to idle and resume wake-word scanning.
   * cache=true only for fixed phrases (greetings/goodbyes/fixed replies).
   */
  _say(text, { continueListening = false, standby = false, cache = false, grace = FOLLOWUP_MS } = {}) {
    this.sm.force('speaking');
    const done = () => {
      if (continueListening) {
        this.sm.force('listening');
        this.simulator.start('listening');
        if (this.voice) this.voice.resumeCommand(grace);
      } else {
        if (standby) this.widgets.hideAll();
        this.sm.force('idle');
        if (this.voice) this.voice.resumeWake();
      }
    };
    if (this.speech) this.speech.speak(text, done, { cache });
    else this._later(done, 1500);
  }

  _respond(widgetId) {
    this.sm.force('thinking');
    this._later(() => {
      this.sm.force('speaking');
      this.simulator.start('speaking');
      if (widgetId) this.widgets.show(widgetId, 16000);
      const speakMs = 2600 + Math.random() * 2200;
      this._later(() => {
        this.simulator.stop();
        this.sm.force('idle');
      }, speakMs);
    }, 800 + Math.random() * 600);
  }

  deactivate() {
    this._clear();
    this.awaitingCode = false;
    if (this.speech) this.speech.cancel();
    this.simulator.stop();
    this.widgets.hideAll();
    if (this.voice) this.voice.resumeWake();
    this.sm.force('idle');
  }

  /** Quietly return to idle (e.g. follow-up window elapsed with no reply). */
  abort() {
    this._clear();
    this.awaitingCode = false;
    if (this.voice) this.voice.resumeWake();
    this.sm.force('idle');
  }
}
