/* ============================================================
   Assistant - high-level orchestration of JARVIS behavior.
   Maps user/AI intents to a state pipeline + widget reveals +
   simulated audio. Today driven by tap/hold and the debug
   "ASK" buttons; tomorrow by the AI/server.
   ============================================================ */
import { bus } from './EventBus.js';
import { upcomingAppointments } from './Appointments.js';

/** Topic -> widget that should appear when that topic is requested. */
export const TOPIC_WIDGET = {
  orario: 'clock',
  meteo: 'weather',
  sistema: 'stats',
  link: 'links',
  musica: 'wave',
};

/** Map a free-form spoken command to a widget to reveal. */
const COMMAND_PATTERNS = [
  { re: /(meteo|tempo|prevision|temperatur|piov)/i, widget: 'weather' },
  { re: /(ora|orari|che ore|data|giorno|adesso)/i, widget: 'clock' },
  { re: /(sistem|cpu|memori|stato|diagnos|potenz)/i, widget: 'stats' },
  { re: /(musica|canzon|brano|suona|playlist)/i, widget: 'wave' },
  { re: /(link|collegament|applicazion|\bapp\b)/i, widget: 'links' },
];

export function widgetForCommand(text = '') {
  for (const p of COMMAND_PATTERNS) if (p.re.test(text)) return p.widget;
  return null;
}

/** Spoken replies when JARVIS is activated. */
const GREETINGS = [
  'Dimmi',
  'Al tuo servizio Alex',
  'Di cosa hai bisogno?',
  'Presente',
  'Bentornato Signore.',
  'Tutti i sistemi sono online.',
];

/** Spoken farewells when JARVIS is sent to standby. */
const GOODBYES = [
  'Vado in standby, Signore. Mi richiami quando ha bisogno.',
  'Mi metto in attesa. A presto, Signore.',
  'Sistemi in pausa. Resto in ascolto del suo richiamo, Signore.',
  'Mi disattivo, Signore. Sarò qui non appena pronuncerà il mio nome.',
  'Arrivederci, Signore. È stato un piacere.',
  'Torno in modalità riposo. A sua disposizione quando vorrà.',
];

/** Fixed spoken phrase for actions not yet implemented. */
const DISABLED_PHRASE = 'Funzione non abilitata, mio Signore.';
const ERROR_PHRASE = 'Mi perdoni Signore, ho un problema di connessione.';
const FALLBACK_CONV = 'Temo di non avere una risposta al momento, Signore.';
const MUSIC_NOT_FOUND = 'Non trovo questo brano in libreria, Signore.';

/** Access-code gate phrases. */
const ACCESS_PROMPT = 'Codice di attivazione, Signore.';
const ACCESS_GRANTED = 'Identità confermata. Bentornato, Signore.';
const ACCESS_DENIED = 'Codice errato, Signore. Accesso negato.';

/** How long JARVIS keeps listening for a follow-up after a conversation reply. */
const FOLLOWUP_MS = 5000;

/**
 * Every phrase JARVIS speaks that is NOT generated by the AI.
 * These get pre-cached so ElevenLabs bills each one only once.
 */
export const FIXED_PHRASES = [
  ...GREETINGS,
  ...GOODBYES,
  DISABLED_PHRASE,
  ERROR_PHRASE,
  FALLBACK_CONV,
  MUSIC_NOT_FOUND,
  ACCESS_PROMPT,
  ACCESS_GRANTED,
  ACCESS_DENIED,
];

export class Assistant {
  constructor({ sm, simulator, widgets, speech = null, voice = null, ai = null, auth = null, music = null, library = null, playlists = null, appointments = null, push = null, apptWidget = null }) {
    this.sm = sm;
    this.simulator = simulator;
    this.widgets = widgets;
    this.speech = speech;
    this.voice = voice;
    this.ai = ai;
    this.auth = auth;
    this.music = music;     // MusicPlayer
    this.library = library; // MusicLibrary
    this.playlists = playlists; // Playlists API client
    this.appointments = appointments; // Appointments API client
    this.push = push;       // Web Push registration
    this.apptWidget = apptWidget; // upcoming-reminders HUD widget
    this.musicHistory = []; // recently played tracks (for "previous")
    this.queue = [];        // active playlist queue (tracks)
    this.queueIdx = -1;     // position within the queue
    // Access session persists across reloads / PWA restarts: once unlocked,
    // JARVIS won't ask for the code again on this device.
    this.authenticated = Assistant._loadAuth();
    this.awaitingCode = false;  // next utterance is treated as the code
    this.timers = new Set();
    this.wakeTimer = null;

    // the waveform follows the audio states automatically
    bus.on('state:change', ({ to }) => {
      if (to === 'listening' || to === 'speaking') this.widgets.show('wave');
      else this.widgets.hide('wave');
    });
  }

  static _loadAuth() {
    try { return localStorage.getItem('jarvis-auth') === '1'; } catch (e) { return false; }
  }

  _persistAuth(on) {
    this.authenticated = on;
    try {
      if (on) localStorage.setItem('jarvis-auth', '1');
      else localStorage.removeItem('jarvis-auth');
    } catch (e) { /* private mode: keep in-memory only */ }
  }

  _armWake() {
    clearTimeout(this.wakeTimer);
    this.wakeTimer = setTimeout(() => {
      if (this.sm.is('wake')) this.sm.force('idle');
    }, 8000);
  }

  /** Speak a random greeting (sphere reacts to the real voice), then run onDone. */
  greet(onDone) {
    this._clear();
    if (this.voice) this.voice.hold(); // don't transcribe our own voice
    this.sm.force('speaking');
    const phrase = GREETINGS[(Math.random() * GREETINGS.length) | 0];
    if (this.speech) {
      // NeuralTTS drives the audio level itself (real amplitude). Fixed -> cache.
      this.speech.speak(phrase, () => { if (onDone) onDone(); }, { cache: true });
    } else {
      this._later(() => { if (onDone) onDone(); }, 700);
    }
  }

  _later(fn, ms) {
    const id = setTimeout(() => { this.timers.delete(id); fn(); }, ms);
    this.timers.add(id);
    return id;
  }

  _clear() {
    for (const id of this.timers) clearTimeout(id);
    this.timers.clear();
    clearTimeout(this.wakeTimer);
  }

  /** Tap on the sphere: activate (with greeting), or deactivate. */
  wake() {
    if (this.sm.is('idle')) {
      // First activation while locked: no greeting, ask for the code.
      if (this.auth && !this.authenticated) {
        this._requestCode();
        return;
      }
      this.greet(() => {
        this.sm.force('wake');
        this._armWake();
        if (this.voice) this.voice.resumeWake();
      });
    } else {
      this.deactivate();
    }
  }

  /** Press-and-hold begins: listening. */
  startListening() {
    this._clear();
    this.sm.force('listening');
    this.simulator.start('listening');
  }

  /** Release after hold: process then respond (no specific widget). */
  endListening() {
    this._clear();
    this.simulator.stop();
    this._respond(null);
  }

  /** A concrete request (e.g. from voice/AI): respond + reveal widget. */
  request(topic) {
    this._clear();
    this.simulator.stop();
    this._respond(TOPIC_WIDGET[topic] || null);
  }

  /**
   * Ask for the activation code instead of greeting (used while locked).
   * Goes straight to listening for the spoken code.
   */
  _requestCode() {
    this._clear();
    if (this.voice) this.voice.hold();
    this.awaitingCode = true;
    bus.emit('ai:result', { text: '', intent: 'access_required', reply: '' });
    this._say(ACCESS_PROMPT, { continueListening: true, grace: 8000, cache: true });
  }

  /** Wake word recognized: greet, then start listening for the command. */
  voiceWake() {
    // First activation while locked: no greeting, ask for the code.
    if (this.auth && !this.authenticated) {
      this._requestCode();
      return;
    }
    // While music plays, skip the greeting and go straight to listening so
    // "stop" / "skip" feel instant (music ducks during the listening state).
    if (this.music && this.music.playing) {
      this._clear();
      if (this.voice) this.voice.hold();
      this.sm.force('listening');
      this.simulator.start('listening');
      if (this.voice) this.voice.resumeCommand();
      return;
    }
    this.greet(() => {
      this.sm.force('listening');
      this.simulator.start('listening');
      if (this.voice) this.voice.resumeCommand();
    });
  }

  /**
   * Spoken command captured: ask the AI, classify the intent, then
   * speak. Only "conversation" gets a real reply; the other actions
   * are not implemented yet and get a fixed phrase.
   */
  async voiceEnd(text) {
    this._clear();
    this.simulator.stop();
    if (this.voice) this.voice.hold();

    // ---- access gate: must unlock with the code before talking ----
    if (this.auth && !this.authenticated) {
      this.sm.force('thinking');
      if (this.awaitingCode) {
        const ok = await this.auth.verify(text);
        bus.emit('ai:result', { text, intent: ok ? 'access_granted' : 'access_denied', reply: '' });
        if (ok) {
          this._persistAuth(true);
          this.awaitingCode = false;
          this._say(ACCESS_GRANTED, { continueListening: true, cache: true });
        } else {
          this._say(ACCESS_DENIED, { continueListening: true, grace: 8000, cache: true });
        }
        return;
      }
      // first command while locked: ask for the activation code
      this.awaitingCode = true;
      bus.emit('ai:result', { text, intent: 'access_required', reply: '' });
      this._say(ACCESS_PROMPT, { continueListening: true, grace: 8000, cache: true });
      return;
    }

    this.sm.force('thinking');

    let result = { intent: 'conversation', reply: '' };
    if (this.ai) {
      const nowPlaying = this.music && this.music.current ? this.music.current : null;
      result = await this.ai.ask(text, { nowPlaying });
    }
    bus.emit('ai:result', {
      text,
      intent: result.intent,
      reply: result.reply,
      remembered: result.remembered || [],
      error: result.error,
    });

    // Standby: say a farewell (fixed -> cached), then go fully to standby.
    if (result.intent === 'standby') {
      const bye = GOODBYES[(Math.random() * GOODBYES.length) | 0];
      this._say(bye, { standby: true, cache: true });
      return;
    }

    // Music: JARVIS stays silent and just drives the player + widget.
    if (result.intent === 'music') {
      this._handleMusic(result, text);
      return;
    }

    // Appointment: save it server-side; the cron + Web Push deliver reminders.
    if (result.intent === 'appointment') {
      await this._handleAppointment(result);
      return;
    }

    // Update the access code (only reachable once authenticated).
    if (result.intent === 'update_access_code') {
      const newCode = (result.accessCode || '').trim();
      if (!newCode) {
        this._say('Non ho colto il nuovo codice, Signore.', { continueListening: true, cache: false });
        return;
      }
      const ok = this.auth ? await this.auth.update(newCode) : false;
      if (ok) {
        this._say(`Codice di accesso aggiornato. Il nuovo codice è: ${newCode}, Signore.`,
          { continueListening: true, cache: false });
      } else {
        this._say('Non sono riuscito ad aggiornare il codice, Signore.', { continueListening: true, cache: false });
      }
      return;
    }

    let replyText;
    let keepListening = false;
    let cache = true; // fixed phrases are cached; dynamic replies are not
    if (result.intent === 'conversation') {
      if (result.reply) {
        replyText = result.reply;
        keepListening = true;       // stay open for the user's follow-up
        cache = false;              // dynamic -> never cache
      } else if (result.error) {
        replyText = ERROR_PHRASE;   // fixed
        keepListening = true;       // transient (e.g. rate limit) -> let them retry
      } else {
        replyText = FALLBACK_CONV;  // fixed
      }
    } else {
      replyText = DISABLED_PHRASE; // music/appointment/note: not enabled yet
    }
    this._say(replyText, { continueListening: keepListening, cache });
  }

  /**
   * Music intent: play / shuffle / next / prev / pause / resume / stop,
   * all without speaking. The "now playing" widget shows title + artist
   * with a bass-reactive equalizer.
   */
  _handleMusic(result, utterance = '') {
    const action = result.musicAction || (result.musicStop ? 'stop' : 'play');

    // ---- playlist management (these may speak a short confirmation) ----
    if (action && action.indexOf('playlist_') === 0) {
      this._handlePlaylist(action, result, utterance);
      return;
    }

    if (action === 'stop') { this.musicStop(); this._idleQuiet(); return; }
    if (action === 'pause') { if (this.music) this.music.pause(); this._idleQuiet(); return; }
    if (action === 'resume') {
      if (this.music) { this.music.resume(); this.widgets.show('music'); }
      this._idleQuiet();
      return;
    }
    if (action === 'shuffle') {
      this._clearQueue(); // break out of any playlist into free shuffle
      if (this.musicNext()) this._idleQuiet();
      else this._say(MUSIC_NOT_FOUND, { continueListening: true, cache: true });
      return;
    }
    if (action === 'next') {
      if (this.musicNext()) this._idleQuiet();
      else this._say(MUSIC_NOT_FOUND, { continueListening: true, cache: true });
      return;
    }
    if (action === 'prev') {
      if (this.musicPrev()) this._idleQuiet();
      else this._say(MUSIC_NOT_FOUND, { continueListening: true, cache: true });
      return;
    }

    // "un'altra di questo artista": same artist, different track
    if (result.musicArtist && !result.musicTitle && this.library && this.music && this.music.current) {
      const cur = this.music.current.file;
      const sameArtist = this.library.byArtist(result.musicArtist, cur);
      if (sameArtist) { this.playTrack(sameArtist); this._idleQuiet(); return; }
    }

    // play: a specific request, or generic -> random fallback
    const track = this.library
      ? this.library.resolve(result.musicArtist, result.musicTitle, utterance)
      : null;
    if (track) { this.playTrack(track); this._idleQuiet(); return; }
    if (this.musicNext()) this._idleQuiet();
    else this._say(MUSIC_NOT_FOUND, { continueListening: true, cache: true });
  }

  /**
   * Playlist actions: play / create / add / remove / delete / list.
   * Playing is silent (like music); management speaks a short confirmation.
   */
  async _handlePlaylist(action, result, utterance = '') {
    if (!this.playlists || !this.library) {
      this._say('Le playlist non sono disponibili, Signore.', { continueListening: true, cache: false });
      return;
    }
    const name = (result.playlistName || '').trim();
    const picks = Array.isArray(result.playlistTracks) ? result.playlistTracks : [];

    if (action === 'playlist_list') {
      const all = await this.playlists.list();
      if (!all.length) { this._say('Non ha ancora nessuna playlist, Signore.', { continueListening: false, cache: false }); return; }
      const names = all.map((p) => p.name).join(', ');
      this._say(`Le sue playlist, Signore: ${names}.`, { continueListening: false, cache: false });
      return;
    }

    if (!name) {
      this._say('Non ho colto il nome della playlist, Signore.', { continueListening: true, cache: false });
      return;
    }

    if (action === 'playlist_play') {
      const pl = await this.playlists.get(name);
      if (!pl || !Array.isArray(pl.tracks) || !pl.tracks.length) {
        this._say(`Non trovo la playlist ${name}, Signore.`, { continueListening: true, cache: false });
        return;
      }
      this._playQueue(pl.tracks);
      this._idleQuiet();
      return;
    }

    if (action === 'playlist_delete') {
      const r = await this.playlists.delete(name);
      if (r && r.ok) this._say(`Playlist ${name} eliminata, Signore.`, { continueListening: false, cache: false });
      else this._say(`Non trovo la playlist ${name}, Signore.`, { continueListening: true, cache: false });
      return;
    }

    // create / add / remove all work on a resolved track list
    const tracks = this.library.resolveMany(picks.length ? picks : [utterance]);

    if (action === 'playlist_remove') {
      const titles = picks.map((p) => (typeof p === 'string' ? p : (p && p.title) || '')).filter(Boolean);
      const r = await this.playlists.remove(name, {
        files: tracks.map((t) => t.file),
        titles,
      });
      const n = r && r.playlist ? (r.playlist.tracks || []).length : 0;
      if (r && r.ok) this._say(`Aggiornata la playlist ${name}: ${n} brani, Signore.`, { continueListening: false, cache: false });
      else this._say(`Non trovo la playlist ${name}, Signore.`, { continueListening: true, cache: false });
      return;
    }

    if (!tracks.length) {
      this._say('Non ho riconosciuto i brani da inserire, Signore.', { continueListening: true, cache: false });
      return;
    }

    const r = action === 'playlist_add'
      ? await this.playlists.add(name, tracks)
      : await this.playlists.create(name, tracks);
    if (r && r.ok) {
      const n = r.playlist ? (r.playlist.tracks || []).length : tracks.length;
      const verb = action === 'playlist_add' ? 'Aggiornata' : 'Creata';
      this._say(`${verb} la playlist ${name} con ${n} brani, Signore.`, { continueListening: false, cache: false });
    } else {
      this._say(`Non sono riuscito a salvare la playlist ${name}, Signore.`, { continueListening: true, cache: false });
    }
  }

  /** Play a specific track, remembering the previous one for "prev". */
  playTrack(track, { keepQueue = false } = {}) {
    if (!track || !this.music) return;
    if (!keepQueue) this._clearQueue();
    if (this.music.current) {
      this.musicHistory.push(this.music.current);
      if (this.musicHistory.length > 50) this.musicHistory.shift();
    }
    this.music.play(track);
    this.widgets.show('music');
  }

  /** Start playing a queue of tracks (a playlist). */
  _playQueue(tracks) {
    this.queue = (tracks || []).filter((t) => t && t.file);
    this.queueIdx = 0;
    if (this.queue.length) this.playTrack(this.queue[0], { keepQueue: true });
  }

  _clearQueue() {
    this.queue = [];
    this.queueIdx = -1;
  }

  /**
   * Advance playback: within an active playlist queue step to the next
   * track; otherwise play a random one (shuffle / skip).
   * @returns {boolean} played
   */
  musicNext() {
    if (!this.music) return false;
    // queued playlist: advance to the next track in order
    if (this.queue.length && this.queueIdx >= 0) {
      if (this.queueIdx < this.queue.length - 1) {
        this.queueIdx++;
        this.playTrack(this.queue[this.queueIdx], { keepQueue: true });
        return true;
      }
      this._clearQueue(); // playlist finished -> stop here
      return false;
    }
    if (!this.library) return false;
    const cur = this.music.current && this.music.current.file;
    const t = this.library.random(cur);
    if (!t) return false;
    this.playTrack(t);
    return true;
  }

  /** Go back to the previously played track. @returns {boolean} played */
  musicPrev() {
    const prev = this.musicHistory.pop();
    if (prev && this.music) {
      this.music.play(prev); // not via playTrack: don't re-stack history
      this.widgets.show('music');
      return true;
    }
    return this.musicNext();
  }

  /** Stop playback and hide the widget. */
  musicStop() {
    this._clearQueue();
    if (this.music) this.music.stop();
    this.widgets.hide('music');
  }

  /**
   * Appointment intent: add / list / delete. Add persists server-side (cron +
   * Web Push deliver reminders); list speaks the upcoming ones; delete removes
   * a matching one. The HUD widget mirrors the upcoming reminders.
   */
  async _handleAppointment(result) {
    const ops = Array.isArray(result.appointmentOps) ? result.appointmentOps : [];
    if (!this.appointments) {
      this._say('L\u2019agenda non \u00e8 disponibile, Signore.', { continueListening: true, cache: false });
      return;
    }
    if (!ops.length) {
      this._say('Non ho colto i dettagli dell\u2019impegno, Signore.', { continueListening: true, cache: false });
      return;
    }

    // Pure "che impegni ho?" request.
    if (ops.length === 1 && ops[0].action === 'list') { await this._handleApptList(); return; }

    // Execute every operation in order, collecting spoken clauses.
    const clauses = [];
    let wantsList = false;
    for (const op of ops) {
      if (op.action === 'list') { wantsList = true; continue; }
      const clause = op.action === 'delete'
        ? await this._apptDeleteOp(op)
        : await this._apptAddOp(op);
      if (clause) clauses.push(clause);
    }

    if (this.push) this.push.enable(); // ensure this device can receive reminders
    this._refreshApptWidget();

    if (wantsList) {
      const listClause = await this._apptListClause();
      if (listClause) clauses.push(listClause);
    }
    if (!clauses.length) {
      this._say('Non sono riuscito a completare la richiesta, Signore.', { continueListening: true, cache: false });
      return;
    }
    this._say(`${clauses.join('. ')}, Signore.`, { continueListening: false, cache: false });
  }

  /** Add one appointment; returns a spoken clause (or '' on failure). */
  async _apptAddOp(op) {
    const title = (op.title || '').trim();
    const datetime = (op.datetime || '').trim();
    if (!title || !datetime) return '';
    const r = await this.appointments.add({
      title,
      datetime,
      all_day: !!op.allDay,
      recurrence: op.recurrence || 'none',
      reminders: Array.isArray(op.reminders) ? op.reminders : [],
      notes: op.notes || '',
    });
    if (!(r && r.ok)) return '';
    const appt = r.appointment || { title, datetime, all_day: op.allDay, recurrence: op.recurrence };
    const when = this._whenText(appt.datetime, appt.all_day);
    const rec = { daily: ' ogni giorno', weekly: ' ogni settimana', monthly: ' ogni mese', yearly: ' ogni anno' }[appt.recurrence] || '';
    return `Fissato ${appt.title} per ${when}${rec}`;
  }

  /** Delete appointments (all / by date / by title); returns a spoken clause. */
  async _apptDeleteOp(op) {
    const scope = op.deleteScope || (op.deleteDate ? 'date' : (op.title ? 'title' : ''));
    if (scope === 'all') {
      const r = await this.appointments.deleteAll();
      return (r && r.deleted) ? 'Cancellati tutti gli impegni' : 'Non c\u2019erano impegni da cancellare';
    }
    if (scope === 'date' && op.deleteDate) {
      const r = await this.appointments.deleteByDate(op.deleteDate);
      const label = this._dayLabel(op.deleteDate);
      return (r && r.deleted) ? `Cancellati gli impegni di ${label}` : `Non ha impegni ${label}`;
    }
    const title = (op.title || '').trim();
    if (!title) return '';
    const r = await this.appointments.deleteByTitle(title);
    if (r && r.deleted) {
      const t = (r.titles && r.titles[0]) || title;
      return r.deleted > 1 ? `Cancellati ${r.deleted} impegni` : `Cancellato ${t}`;
    }
    return `Non trovo ${title} in agenda`;
  }

  /** Speak (and show) the next few upcoming reminders. */
  async _handleApptList() {
    const clause = await this._apptListClause();
    if (!clause) {
      this._say('Non ha impegni in programma, Signore.', { continueListening: false, cache: false });
      return;
    }
    this._say(`${clause}, Signore.`, { continueListening: false, cache: false });
  }

  /** Build the spoken upcoming-reminders clause and reveal the widget. */
  async _apptListClause() {
    const appts = await this.appointments.list();
    const up = upcomingAppointments(appts, 3);
    this._refreshApptWidget();
    if (!up.length) return '';
    if (this.apptWidget) this.widgets.show('appointments', 18000);
    const parts = up.map(({ appt, occ }) => `${appt.title}, ${this._whenTextDate(occ, appt.all_day)}`);
    const lead = up.length === 1 ? 'Ha un impegno in programma' : `Ha ${up.length} impegni in programma`;
    return `${lead}: ${parts.join('; ')}`;
  }

  _refreshApptWidget() {
    if (this.apptWidget && this.apptWidget.refresh) this.apptWidget.refresh();
  }

  /** Italian spoken date from a "YYYY-MM-DD HH:MM" string. */
  _whenText(datetime, allDay) {
    const d = new Date(String(datetime).replace(' ', 'T'));
    if (isNaN(d)) return datetime;
    return this._whenTextDate(d, allDay);
  }

  /** Italian spoken date from a Date; omits the time for all-day events. */
  _whenTextDate(date, allDay) {
    try {
      const opts = allDay
        ? { weekday: 'long', day: 'numeric', month: 'long' }
        : { weekday: 'long', day: 'numeric', month: 'long', hour: '2-digit', minute: '2-digit' };
      let s = new Intl.DateTimeFormat('it-IT', opts).format(date);
      if (!allDay) s = s.replace(',', ' alle');
      return s;
    } catch (e) { return ''; }
  }

  /** "oggi" / "domani" / "il 10 giugno" for a "YYYY-MM-DD" date. */
  _dayLabel(dateYmd) {
    const m = String(dateYmd).match(/^(\d{4})-(\d{2})-(\d{2})/);
    if (!m) return 'quel giorno';
    const d = new Date(+m[1], +m[2] - 1, +m[3]);
    const now = new Date();
    if (d.toDateString() === now.toDateString()) return 'oggi';
    const tom = new Date(now); tom.setDate(now.getDate() + 1);
    if (d.toDateString() === tom.toDateString()) return 'domani';
    try {
      return 'il ' + new Intl.DateTimeFormat('it-IT', { day: 'numeric', month: 'long' }).format(d);
    } catch (e) { return 'quel giorno'; }
  }

  /** Return to idle without speaking (used after starting/stopping music). */
  _idleQuiet() {
    this.simulator.stop();
    this.sm.force('idle');
    if (this.voice) this.voice.resumeWake();
  }

  /**
   * Speak a phrase, then:
   *  - continueListening: stay in listening mode for FOLLOWUP_MS (no wake word);
   *  - standby: hide widgets and return to idle (wake word required again);
   *  - default: return to idle and resume wake-word scanning.
   * cache=true only for fixed phrases (greetings/goodbyes/fixed replies).
   */
  _say(text, { continueListening = false, standby = false, cache = false, grace = FOLLOWUP_MS } = {}) {
    this.sm.force('speaking');
    const done = () => {
      if (continueListening) {
        this.sm.force('listening');
        this.simulator.start('listening');
        if (this.voice) this.voice.resumeCommand(grace);
      } else {
        if (standby) this.widgets.hideAll();
        this.sm.force('idle');
        if (this.voice) this.voice.resumeWake();
      }
    };
    if (this.speech) this.speech.speak(text, done, { cache });
    else this._later(done, 1500);
  }

  _respond(widgetId) {
    this.sm.force('thinking');
    this._later(() => {
      this.sm.force('speaking');
      this.simulator.start('speaking');
      if (widgetId) this.widgets.show(widgetId, 16000);
      const speakMs = 2600 + Math.random() * 2200;
      this._later(() => {
        this.simulator.stop();
        this.sm.force('idle');
      }, speakMs);
    }, 800 + Math.random() * 600);
  }

  deactivate() {
    this._clear();
    this.awaitingCode = false;
    if (this.speech) this.speech.cancel();
    this.simulator.stop();
    this.widgets.hideAll();
    if (this.voice) this.voice.resumeWake();
    this.sm.force('idle');
  }

  /** Quietly return to idle (e.g. follow-up window elapsed with no reply). */
  abort() {
    this._clear();
    this.awaitingCode = false;
    if (this.voice) this.voice.resumeWake();
    this.sm.force('idle');
  }
}
