/* ============================================================
   Assistant - high-level orchestration of JARVIS behavior.
   Maps user/AI intents to a state pipeline + widget reveals +
   simulated audio. Today driven by tap/hold and the debug
   "ASK" buttons; tomorrow by the AI/server.
   ============================================================ */
import { bus } from './EventBus.js';

/** Topic -> widget that should appear when that topic is requested. */
export const TOPIC_WIDGET = {
  orario: 'clock',
  meteo: 'weather',
  sistema: 'stats',
  link: 'links',
  musica: 'wave',
};

/** Map a free-form spoken command to a widget to reveal. */
const COMMAND_PATTERNS = [
  { re: /(meteo|tempo|prevision|temperatur|piov)/i, widget: 'weather' },
  { re: /(ora|orari|che ore|data|giorno|adesso)/i, widget: 'clock' },
  { re: /(sistem|cpu|memori|stato|diagnos|potenz)/i, widget: 'stats' },
  { re: /(musica|canzon|brano|suona|playlist)/i, widget: 'wave' },
  { re: /(link|collegament|applicazion|\bapp\b)/i, widget: 'links' },
];

export function widgetForCommand(text = '') {
  for (const p of COMMAND_PATTERNS) if (p.re.test(text)) return p.widget;
  return null;
}

/** Spoken replies when JARVIS is activated. */
const GREETINGS = [
  'Dimmi',
  'Al tuo servizio Alex',
  'Di cosa hai bisogno?',
  'Presente',
  'Bentornato Signore.',
  'Tutti i sistemi sono online.',
];

/** Spoken farewells when JARVIS is sent to standby. */
const GOODBYES = [
  'Vado in standby, Signore. Mi richiami quando ha bisogno.',
  'Mi metto in attesa. A presto, Signore.',
  'Sistemi in pausa. Resto in ascolto del suo richiamo, Signore.',
  'Mi disattivo, Signore. Sarò qui non appena pronuncerà il mio nome.',
  'Arrivederci, Signore. È stato un piacere.',
  'Torno in modalità riposo. A sua disposizione quando vorrà.',
];

/** Fixed spoken phrase for actions not yet implemented. */
const DISABLED_PHRASE = 'Funzione non abilitata, mio Signore.';
const ERROR_PHRASE = 'Mi perdoni Signore, ho un problema di connessione.';
const FALLBACK_CONV = 'Temo di non avere una risposta al momento, Signore.';
const MUSIC_NOT_FOUND = 'Non trovo questo brano in libreria, Signore.';

/** Access-code gate phrases. */
const ACCESS_PROMPT = 'Codice di attivazione, Signore.';
const ACCESS_GRANTED = 'Identità confermata. Bentornato, Signore.';
const ACCESS_DENIED = 'Codice errato, Signore. Accesso negato.';

/** How long JARVIS keeps listening for a follow-up after a conversation reply. */
const FOLLOWUP_MS = 5000;

/**
 * Every phrase JARVIS speaks that is NOT generated by the AI.
 * These get pre-cached so ElevenLabs bills each one only once.
 */
export const FIXED_PHRASES = [
  ...GREETINGS,
  ...GOODBYES,
  DISABLED_PHRASE,
  ERROR_PHRASE,
  FALLBACK_CONV,
  MUSIC_NOT_FOUND,
  ACCESS_PROMPT,
  ACCESS_GRANTED,
  ACCESS_DENIED,
];

export class Assistant {
  constructor({ sm, simulator, widgets, speech = null, voice = null, ai = null, auth = null, music = null, library = null }) {
    this.sm = sm;
    this.simulator = simulator;
    this.widgets = widgets;
    this.speech = speech;
    this.voice = voice;
    this.ai = ai;
    this.auth = auth;
    this.music = music;     // MusicPlayer
    this.library = library; // MusicLibrary
    this.musicHistory = []; // recently played tracks (for "previous")
    this.authenticated = false; // session unlocked via the access code
    this.awaitingCode = false;  // next utterance is treated as the code
    this.timers = new Set();
    this.wakeTimer = null;

    // the waveform follows the audio states automatically
    bus.on('state:change', ({ to }) => {
      if (to === 'listening' || to === 'speaking') this.widgets.show('wave');
      else this.widgets.hide('wave');
    });
  }

  _armWake() {
    clearTimeout(this.wakeTimer);
    this.wakeTimer = setTimeout(() => {
      if (this.sm.is('wake')) this.sm.force('idle');
    }, 8000);
  }

  /** Speak a random greeting (sphere reacts to the real voice), then run onDone. */
  greet(onDone) {
    this._clear();
    if (this.voice) this.voice.hold(); // don't transcribe our own voice
    this.sm.force('speaking');
    const phrase = GREETINGS[(Math.random() * GREETINGS.length) | 0];
    if (this.speech) {
      // NeuralTTS drives the audio level itself (real amplitude). Fixed -> cache.
      this.speech.speak(phrase, () => { if (onDone) onDone(); }, { cache: true });
    } else {
      this._later(() => { if (onDone) onDone(); }, 700);
    }
  }

  _later(fn, ms) {
    const id = setTimeout(() => { this.timers.delete(id); fn(); }, ms);
    this.timers.add(id);
    return id;
  }

  _clear() {
    for (const id of this.timers) clearTimeout(id);
    this.timers.clear();
    clearTimeout(this.wakeTimer);
  }

  /** Tap on the sphere: activate (with greeting), or deactivate. */
  wake() {
    if (this.sm.is('idle')) {
      // First activation while locked: no greeting, ask for the code.
      if (this.auth && !this.authenticated) {
        this._requestCode();
        return;
      }
      this.greet(() => {
        this.sm.force('wake');
        this._armWake();
        if (this.voice) this.voice.resumeWake();
      });
    } else {
      this.deactivate();
    }
  }

  /** Press-and-hold begins: listening. */
  startListening() {
    this._clear();
    this.sm.force('listening');
    this.simulator.start('listening');
  }

  /** Release after hold: process then respond (no specific widget). */
  endListening() {
    this._clear();
    this.simulator.stop();
    this._respond(null);
  }

  /** A concrete request (e.g. from voice/AI): respond + reveal widget. */
  request(topic) {
    this._clear();
    this.simulator.stop();
    this._respond(TOPIC_WIDGET[topic] || null);
  }

  /**
   * Ask for the activation code instead of greeting (used while locked).
   * Goes straight to listening for the spoken code.
   */
  _requestCode() {
    this._clear();
    if (this.voice) this.voice.hold();
    this.awaitingCode = true;
    bus.emit('ai:result', { text: '', intent: 'access_required', reply: '' });
    this._say(ACCESS_PROMPT, { continueListening: true, grace: 8000, cache: true });
  }

  /** Wake word recognized: greet, then start listening for the command. */
  voiceWake() {
    // First activation while locked: no greeting, ask for the code.
    if (this.auth && !this.authenticated) {
      this._requestCode();
      return;
    }
    this.greet(() => {
      this.sm.force('listening');
      this.simulator.start('listening');
      if (this.voice) this.voice.resumeCommand();
    });
  }

  /**
   * Spoken command captured: ask the AI, classify the intent, then
   * speak. Only "conversation" gets a real reply; the other actions
   * are not implemented yet and get a fixed phrase.
   */
  async voiceEnd(text) {
    this._clear();
    this.simulator.stop();
    if (this.voice) this.voice.hold();

    // ---- access gate: must unlock with the code before talking ----
    if (this.auth && !this.authenticated) {
      this.sm.force('thinking');
      if (this.awaitingCode) {
        const ok = await this.auth.verify(text);
        bus.emit('ai:result', { text, intent: ok ? 'access_granted' : 'access_denied', reply: '' });
        if (ok) {
          this.authenticated = true;
          this.awaitingCode = false;
          this._say(ACCESS_GRANTED, { continueListening: true, cache: true });
        } else {
          this._say(ACCESS_DENIED, { continueListening: true, grace: 8000, cache: true });
        }
        return;
      }
      // first command while locked: ask for the activation code
      this.awaitingCode = true;
      bus.emit('ai:result', { text, intent: 'access_required', reply: '' });
      this._say(ACCESS_PROMPT, { continueListening: true, grace: 8000, cache: true });
      return;
    }

    this.sm.force('thinking');

    let result = { intent: 'conversation', reply: '' };
    if (this.ai) result = await this.ai.ask(text);
    bus.emit('ai:result', {
      text,
      intent: result.intent,
      reply: result.reply,
      remembered: result.remembered || [],
      error: result.error,
    });

    // Standby: say a farewell (fixed -> cached), then go fully to standby.
    if (result.intent === 'standby') {
      const bye = GOODBYES[(Math.random() * GOODBYES.length) | 0];
      this._say(bye, { standby: true, cache: true });
      return;
    }

    // Music: JARVIS stays silent and just drives the player + widget.
    if (result.intent === 'music') {
      this._handleMusic(result, text);
      return;
    }

    // Update the access code (only reachable once authenticated).
    if (result.intent === 'update_access_code') {
      const newCode = (result.accessCode || '').trim();
      if (!newCode) {
        this._say('Non ho colto il nuovo codice, Signore.', { continueListening: true, cache: false });
        return;
      }
      const ok = this.auth ? await this.auth.update(newCode) : false;
      if (ok) {
        this._say(`Codice di accesso aggiornato. Il nuovo codice è: ${newCode}, Signore.`,
          { continueListening: true, cache: false });
      } else {
        this._say('Non sono riuscito ad aggiornare il codice, Signore.', { continueListening: true, cache: false });
      }
      return;
    }

    let replyText;
    let keepListening = false;
    let cache = true; // fixed phrases are cached; dynamic replies are not
    if (result.intent === 'conversation') {
      if (result.reply) {
        replyText = result.reply;
        keepListening = true;       // stay open for the user's follow-up
        cache = false;              // dynamic -> never cache
      } else if (result.error) {
        replyText = ERROR_PHRASE;   // fixed
        keepListening = true;       // transient (e.g. rate limit) -> let them retry
      } else {
        replyText = FALLBACK_CONV;  // fixed
      }
    } else {
      replyText = DISABLED_PHRASE; // music/appointment/note: not enabled yet
    }
    this._say(replyText, { continueListening: keepListening, cache });
  }

  /**
   * Music intent: play / shuffle / next / prev / pause / resume / stop,
   * all without speaking. The "now playing" widget shows title + artist
   * with a bass-reactive equalizer.
   */
  _handleMusic(result, utterance = '') {
    const action = result.musicAction || (result.musicStop ? 'stop' : 'play');

    if (action === 'stop') { this.musicStop(); this._idleQuiet(); return; }
    if (action === 'pause') { if (this.music) this.music.pause(); this._idleQuiet(); return; }
    if (action === 'resume') {
      if (this.music) { this.music.resume(); this.widgets.show('music'); }
      this._idleQuiet();
      return;
    }
    if (action === 'next' || action === 'shuffle') {
      if (this.musicNext()) this._idleQuiet();
      else this._say(MUSIC_NOT_FOUND, { continueListening: true, cache: true });
      return;
    }
    if (action === 'prev') {
      if (this.musicPrev()) this._idleQuiet();
      else this._say(MUSIC_NOT_FOUND, { continueListening: true, cache: true });
      return;
    }

    // play: a specific request, or generic -> random fallback
    const track = this.library
      ? this.library.resolve(result.musicArtist, result.musicTitle, utterance)
      : null;
    if (track) { this.playTrack(track); this._idleQuiet(); return; }
    if (this.musicNext()) this._idleQuiet();
    else this._say(MUSIC_NOT_FOUND, { continueListening: true, cache: true });
  }

  /** Play a specific track, remembering the previous one for "prev". */
  playTrack(track) {
    if (!track || !this.music) return;
    if (this.music.current) {
      this.musicHistory.push(this.music.current);
      if (this.musicHistory.length > 50) this.musicHistory.shift();
    }
    this.music.play(track);
    this.widgets.show('music');
  }

  /** Play a random track (shuffle / skip). @returns {boolean} played */
  musicNext() {
    if (!this.music || !this.library) return false;
    const cur = this.music.current && this.music.current.file;
    const t = this.library.random(cur);
    if (!t) return false;
    this.playTrack(t);
    return true;
  }

  /** Go back to the previously played track. @returns {boolean} played */
  musicPrev() {
    const prev = this.musicHistory.pop();
    if (prev && this.music) {
      this.music.play(prev); // not via playTrack: don't re-stack history
      this.widgets.show('music');
      return true;
    }
    return this.musicNext();
  }

  /** Stop playback and hide the widget. */
  musicStop() {
    if (this.music) this.music.stop();
    this.widgets.hide('music');
  }

  /** Return to idle without speaking (used after starting/stopping music). */
  _idleQuiet() {
    this.simulator.stop();
    this.sm.force('idle');
    if (this.voice) this.voice.resumeWake();
  }

  /**
   * Speak a phrase, then:
   *  - continueListening: stay in listening mode for FOLLOWUP_MS (no wake word);
   *  - standby: hide widgets and return to idle (wake word required again);
   *  - default: return to idle and resume wake-word scanning.
   * cache=true only for fixed phrases (greetings/goodbyes/fixed replies).
   */
  _say(text, { continueListening = false, standby = false, cache = false, grace = FOLLOWUP_MS } = {}) {
    this.sm.force('speaking');
    const done = () => {
      if (continueListening) {
        this.sm.force('listening');
        this.simulator.start('listening');
        if (this.voice) this.voice.resumeCommand(grace);
      } else {
        if (standby) this.widgets.hideAll();
        this.sm.force('idle');
        if (this.voice) this.voice.resumeWake();
      }
    };
    if (this.speech) this.speech.speak(text, done, { cache });
    else this._later(done, 1500);
  }

  _respond(widgetId) {
    this.sm.force('thinking');
    this._later(() => {
      this.sm.force('speaking');
      this.simulator.start('speaking');
      if (widgetId) this.widgets.show(widgetId, 16000);
      const speakMs = 2600 + Math.random() * 2200;
      this._later(() => {
        this.simulator.stop();
        this.sm.force('idle');
      }, speakMs);
    }, 800 + Math.random() * 600);
  }

  deactivate() {
    this._clear();
    this.awaitingCode = false;
    if (this.speech) this.speech.cancel();
    this.simulator.stop();
    this.widgets.hideAll();
    if (this.voice) this.voice.resumeWake();
    this.sm.force('idle');
  }

  /** Quietly return to idle (e.g. follow-up window elapsed with no reply). */
  abort() {
    this._clear();
    this.awaitingCode = false;
    if (this.voice) this.voice.resumeWake();
    this.sm.force('idle');
  }
}
